version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: mysql_django
    restart: always
    environment:
      - MYSQL_DATABASE= ${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_app
    container_name: django_web
    volumes:
      - .:/app
    ports:
      - "8089:8089"
    depends_on:
      - db
    command: ["sh", "./entrypoint.sh"]
    environment:
      DB_NAME: "${MYSQL_DATABASE}"
      DB_USER: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      DB_HOST: "db"
      DB_PORT: 3306

volumes:
  mysql_data:
